project_name: "keys"
builds:
  - id: keysd
    binary: keysd
    main: ./keysd/main.go
    goos:
      - linux
    goarch:
      - amd64
      - 386
      # - arm
archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_linux_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  prerelease: true
changelog:
  skip: true
nfpms:
  - description: "keys.pub"
    homepage: "https://keys.pub"
    license: MIT
    maintainer: Gabriel Handford <gabrielh@gmail.com>
    replacements:
      386: i386
    formats:
      - deb
      - rpm
