on:
  push:
    branches:
      - v0*
name: Release
jobs:
  release-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
      - name: Import codesign
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: Build
        run: |
          git config --global user.email "keys.pub"
          git config --global user.name "keys.pub"
          git tag -a ${GITHUB_REF##*/} -m ${GITHUB_REF##*/}
          cd service
          goreleaser
          cd ../auth/rpc/plugin
          goreleaser
